# Generated by Django 4.1.4 on 2023-01-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.CharField(max_length=256, unique=True)),
                ("college", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=256)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("FA", "Fall"),
                            ("SP", "Spring"),
                            ("S1", "Summer 1"),
                            ("S2", "Summer 2"),
                        ],
                        max_length=2,
                    ),
                ),
                ("year", models.IntegerField()),
                ("teachers", models.ManyToManyField(to="feedback_man.teacher")),
            ],
        ),
    ]
