# Generated by Django 4.1.4 on 2023-01-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_man", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="college",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
