# Generated by Django 4.1.4 on 2023-01-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_man", "0002_alter_teacher_college_alter_teacher_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_num",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
