# Generated by Django 4.1.4 on 2023-03-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_man", "0004_studentaccount_alter_course_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentaccount",
            name="id",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="id",
        ),
        migrations.AlterField(
            model_name="studentaccount",
            name="student_email",
            field=models.EmailField(
                max_length=254, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(
                max_length=256, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
